export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";

export const POST_BOOKS_REQUEST = "POST_BOOKS_REQUEST";
export const POST_BOOKS_SUCCESS = "POST_BOOKS_SUCCESS";
export const POST_BOOKS_ERROR = "POST_BOOKS_ERROR";
