export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";

export const POST_BOOKS_REQUEST = "POST_BOOKS_REQUEST";
export const POST_BOOKS_SUCCESS = "POST_BOOKS_SUCCESS";
export const POST_BOOKS_ERROR = "POST_BOOKS_ERROR";

export const DELETE_BOOKS_REQUEST = "DELETE_BOOKS_REQUEST";
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_ERROR = "DELETE_BOOKS_ERROR";

export const FETCH_EDIT_BOOKS_REQUEST = "FETCH_EDIT_BOOKS_REQUEST";
export const FETCH_EDIT_BOOKS_SUCCESS = "FETCH_EDIT_BOOKS_SUCCESS";
export const FETCH_EDIT_BOOKS_ERROR = "FETCH_EDIT_BOOKS_ERROR";
